# Generated by Django 5.1.7 on 2025-03-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_app', '0003_customuser_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorinvitetoken',
            name='token',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
