# Generated by Django 5.1.6 on 2025-03-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_app', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorstudent',
            name='attendance_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorstudent',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutorstudent',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
