# Generated by Django 5.1.6 on 2025-03-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_app', '0006_tutorstudent_attendance_time_tutorstudent_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='last_lesson_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='last_lesson_topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
