# Generated by Django 5.1.6 on 2025-03-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_app', '0007_tutorprofile_last_lesson_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='excel_generated',
            field=models.BooleanField(default=False),
        ),
    ]
